name: landing
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  gap: ^3.0.1
  intl: ^0.19.0
  get_it: ^8.0.3
  logger: ^2.6.2
  slang: ^4.11.0
  freezed: ^3.0.6
  injectable: ^2.5.1
  collection: ^1.19.0
  file_saver: ^0.2.14
  flutter_svg: ^2.2.0
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.12.0
  url_launcher: ^6.3.2
  auto_route: ^10.1.0+1
  slang_flutter: ^4.11.0
  shadcn_flutter: ^0.0.24
  device_info_plus: ^11.3.0
  web_smooth_scroll: ^2.0.0
  super_sliver_list: ^0.4.1
  freezed_annotation: ^3.1.0
  theme_tailor_annotation: ^3.0.2
  assorted_layout_widgets: ^11.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.2
  http: ^1.6.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  theme_tailor: ^3.0.3
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.12.0
  slang_build_runner: ^4.11.0
  injectable_generator: ^2.7.0
  auto_route_generator: ^10.0.1
  json_serializable: ^6.9.5

flutter_gen:
  output: lib/core/gen
  integrations:
    image: true
    flutter_svg: true
  colors:
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors

flutter:
  uses-material-design: true
  assets:
  - assets/

  - assets/icons/
  - assets/icons/general/
  - assets/icons/general/link/
  - assets/icons/general/project/
  - assets/icons/contacts/email/
  - assets/icons/contacts/phone/
  - assets/icons/contacts/contact/
  - assets/icons/skills/
  - assets/icons/skills/code/
  - assets/icons/skills/mobile/
  - assets/icons/skills/palette/
  - assets/icons/skills/database/
  - assets/icons/skills/pipeline/
  - assets/icons/skills/lightning/
  
  - assets/images/
  - assets/images/general/
  - assets/images/projects/
  - assets/images/backgrounds/
  - assets/images/contacts/hh/
  - assets/images/contacts/github/
  - assets/images/contacts/linkedin/
  - assets/images/contacts/telegram/
  - assets/images/stores/
  - assets/images/stores/app_store/
  - assets/images/stores/google_play/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Regular.ttf
          weight: 300
        - asset: assets/fonts/Inter/Medium.ttf
          weight: 400
        - asset: assets/fonts/Inter/Bold.ttf
          weight: 700
